<?php

namespace Jclyons52\PagePreview;

class TestCase extends \PHPUnit_Framework_TestCase
{
    public $previewManager;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->previewManager = $this->getMockPreviewManager(__DIR__ . '/data/test.html');
    }
    

    /**
     * @return HandlerStack
     */
    protected function getMockPreviewManager($template)
    {
        $httpMock = new MainHttpInterfaceMock($template);
        return new PreviewManager($httpMock);
    }

    public function previewData()
    {
        return [
            "title" => "Meta title",
            "images" => ["http://www.example.com/imgs/img1.jpg", "http://www.example.com/imgs/img2.jpg"],
            "description" => "Foo bar, bar foo",
            "url" => "http://www.example.com",
            "meta" => [
                "og:title" => "Meta title",
                "og:description" => "Foo bar bar foo",
                "title" => "Meta title",
                "description" => "Foo bar bar foo",
                "og:url" => "http://www.example.com",
                "keywords" => ["test", "thing", "stuff"],
                "apple-mobile-web-app-capable" => "yes",
                "viewport" => "minimal-ui",
            ],
            "media" => false,
        ];
    }
}

class MainHttpInterfaceMock implements HttpInterface
{
    public function __construct($file)
    {
        $this->file = $file;
    }

    public function get($url)
    {
        $body = @file_get_contents($this->file);

        return $body;
    }
}